stages:
  - mirror
  - release

mirror:
  stage: mirror
  script:
    - echo "Release to Github"
  environment:
    name: github
    url: https://github.com/AdmitadSDK/ios_sdk
  only:
    - master
  except:
    - tags

release:
  stage: release
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y git ruby > /dev/null
    - gem install cocoapods > /dev/null
  script:
    - set -e
    - echo "Release to Cocoapods"
    - echo "Tag and version $CI_COMMIT_TAG"
    # cocoapods cannot run as root user
    - useradd --create-home releaser
    - su releaser --command="pod setup --silent > /dev/null"
    - su releaser --command="pod spec lint AdmitadSDK.podspec"
    - su releaser --command="pod trunk push AdmitadSDK.podspec"
  environment:
    name: cocoapods
    url: https://cocoapods.org/pods/AdmitadSDK
  only:
    - tags
